language: node_js
node_js:
  - 10.15.0
cache:
  directories:
    - node_modules
language: node_js
node_js:
- 12.4.0
cache:
  directories:
    - node_modules
dist: trusty
install:
  - npm install
script:
  - npm run test
  - npm run build:lib
notifications:
  email:
  - ebrehault@gmail.com